/**
 * Development seed script.
 *
 * Creates a realistic starting point so the console and public pages show data:
 *   - one platform admin (sees every tenant)
 *   - one demo company (tenant) + its org_admin owner
 *   - one hotel (with generated slug) + rooms + facilities
 *   - one guest reservation (so the dashboard/front desk have something to show)
 *
 * Run AFTER migrations, with the DB env configured:
 *   npm run migrate && npm run seed
 *
 * It is idempotent: if the platform admin already exists it exits without
 * touching anything.
 */

import { sequelize, Hotel, Room, Facility, Reservation, User } from '../models';
import authService from '../services/authService';
import hotelService from '../services/hotelService';
import { v4 as uuidv4 } from 'uuid';

const PLATFORM_ADMIN_EMAIL = 'admin@stayng.test';
const DEMO_PASSWORD = 'Password123!';

async function seed() {
  await sequelize.authenticate();

  const existing = await User.findOne({ where: { email: PLATFORM_ADMIN_EMAIL } });
  if (existing) {
    console.log('↩︎  Seed data already present (platform admin exists). Nothing to do.');
    return;
  }

  console.log('🌱  Seeding StayNG demo data…\n');

  // 1) Platform super-admin — cross-tenant visibility, no company.
  const { user: admin } = await authService.register({
    firstName: 'Platform',
    lastName: 'Admin',
    email: PLATFORM_ADMIN_EMAIL,
    phoneNumber: '2348000000000',
    password: DEMO_PASSWORD,
    type: 'admin',
  });
  console.log(`✓ Platform admin        ${admin.email}`);

  // 2) Demo company (tenant) + its first org_admin, created atomically.
  const { user: owner, company } = await authService.onboardCompany(
    {
      name: 'ABC Hotels Ltd',
      contactEmail: 'company@abchotels.test',
      contactPhone: '2348011111111',
      address: 'Victoria Island, Lagos',
    },
    {
      firstName: 'Ada',
      lastName: 'Obi',
      email: 'owner@abchotels.test',
      phoneNumber: '2348022222222',
      password: DEMO_PASSWORD,
    }
  );
  const companyId = (company as any).id;
  console.log(`✓ Company               ${(company as any).name} (${companyId})`);
  console.log(`✓ Hotel admin           ${owner.email}`);

  // 3) Hotel (slug generated by the service).
  const hotel = await hotelService.createHotel(
    {
      name: 'ABC Hotels & Suites',
      address: '1 Ademola Adetokunbo St, Victoria Island',
      city: 'Lagos',
      state: 'Lagos',
      description: 'A comfortable, modern stay in the heart of Victoria Island.',
      contactEmail: 'reservations@abchotels.test',
      contactPhone: '2348033333333' as any,
      hotelType: 'luxury',
    } as any,
    companyId
  );
  const hotelId = (hotel as any).id;
  console.log(`✓ Hotel                 ${(hotel as any).name}  /h/${(hotel as any).slug}`);

  // 4) Rooms (category must be one of the model's ENUM values).
  const roomSpecs = [
    { category: 'regular', capacity: 2, price: 45000, condition: 'good', description: 'Cosy room with a queen bed and ensuite bathroom.' },
    { category: 'luxury', capacity: 2, price: 85000, condition: 'excellent', description: 'Spacious suite with an ocean view and lounge area.' },
    { category: 'studio apartment', capacity: 4, price: 130000, condition: 'excellent', description: 'Self-contained apartment with kitchenette and living space.' },
  ];
  const rooms = [];
  for (const spec of roomSpecs) {
    const room = await Room.create({
      id: uuidv4(),
      hotelId,
      companyId,
      category: spec.category,
      capacity: spec.capacity,
      checkIn: '14:00:00',
      checkOut: '11:00:00',
      description: spec.description,
      availability: true,
      price: spec.price,
      condition: spec.condition,
    } as any);
    rooms.push(room);
  }
  console.log(`✓ Rooms                 ${rooms.length} created`);

  // 5) Facilities for the hotel.
  await Facility.create({
    id: uuidv4(),
    hotelId,
    companyId,
    wifiInternet: true,
    security: true,
    swimmingPool: true,
    barLounge: true,
  } as any);
  console.log('✓ Facilities            created');

  // 6) A guest reservation (guest checkout — no account) so the dashboard and
  // front desk have something to show. Front desk can look it up by BK-DEMO001.
  const dateIn = new Date();
  const dateOut = new Date();
  dateOut.setDate(dateOut.getDate() + 2);
  await Reservation.create({
    id: uuidv4(),
    hotelId,
    roomId: (rooms[0] as any).id,
    companyId,
    guestName: 'Chidi Okeke',
    guestEmail: 'chidi@guest.test',
    guestPhone: '2348099999999',
    bookingReference: 'BK-DEMO001',
    dateIn,
    dateOut,
    guestCount: 2,
    status: 'pending',
  } as any);
  console.log('✓ Guest reservation     BK-DEMO001');

  console.log('\n✅  Seed complete. Sign-in credentials (password for all):');
  console.log(`    ${DEMO_PASSWORD}\n`);
  console.log(`    Platform admin  →  ${PLATFORM_ADMIN_EMAIL}`);
  console.log(`    Hotel admin     →  ${owner.email}`);
  console.log(`    Public page     →  /h/${(hotel as any).slug}`);
}

seed()
  .then(async () => {
    await sequelize.close();
    process.exit(0);
  })
  .catch(async (err) => {
    console.error('\n❌  Seed failed:', err.message);
    try { await sequelize.close(); } catch { /* ignore */ }
    process.exit(1);
  });
